### ISSUE TITLE
issue with the accuracy

### ISSUE THREAD

**Issue by karimmahalian** [BinLiang-NLP/Sentic-GCN#2]
Hi,

I run the code using this command 

!CUDA_VISIBLE_DEVICES=1 python3 train_bert.py --model_name senticgcn_bert --dataset rest15 --save True --learning_rate 2e-5 --seed 39 --batch_size 16 --hidden_dim 768

But I got a very low accuracy compared to the reported results in ur paper

the obtained accuracy is 61.09% and 25.28% for f1-score and these values are the same for all the running steps and epochs !!

Do u have any idea plz?

Thank u

**Comment by BinLiang-NLP** [comment]
> 

I apologize for the error, I'll fix it ASAP.

**Comment by BinLiang-NLP** [comment]
> Hi,
> 
> I run the code using this command
> 
> !CUDA_VISIBLE_DEVICES=1 python3 train_bert.py --model_name senticgcn_bert --dataset rest15 --save True --learning_rate 2e-5 --seed 39 --batch_size 16 --hidden_dim 768
> 
> But I got a very low accuracy compared to the reported results in ur paper
> 
> the obtained accuracy is 61.09% and 25.28% for f1-score and these values are the same for all the running steps and epochs !!
> 
> Do u have any idea plz?
> 
> Thank u

I have fixed the error. Please let me know if there is any problem. Thanks!

**Comment by karimmahalian** [comment]
Hi,

Thank u for the quick response. However, I ran the code, but I got the same results. Do u think that it can be related to the graph files I generate? Because I have to rename some files to run the code correctly.
Here is the name of the generated files:
generate_sentic_dependency_graph is providing files with graph_sdat_60 extension. So I change it to graph_sdat
For .graph files, I executed the dependency_graph.py file.

Thank u for ur feedback

**Comment by BinLiang-NLP** [comment]
> Hi,
> 
> Thank u for the quick response. However, I ran the code, but I got the same results. Do u think that it can be related to the graph files I generate? Because I have to rename some files to run the code correctly. Here is the name of the generated files: generate_sentic_dependency_graph is providing files with graph_sdat_60 extension. So I change it to graph_sdat For .graph files, I executed the dependency_graph.py file.
> 
> Thank u for ur feedback

Hi,
I have fixed this problem too.
Please use **python generate_sentic_dependency_graph.py** to generate "_.graph_sdat_".
The "_.graph_" and "_.graph_s_" files are two variants of our method for generating graphs.

**Comment by karimmahalian** [comment]
First, a big thanks for ur quick responses, I really appreciate that.
However, the problem still persists

Here are the steps I follow to run the code

!wget https://sentic.net/senticnet-6.0.zip

!unzip /content/senticnet-6.0.zip

!pip install spacy

!python -m spacy download en

!git clone https://github.com/SenticNet/Sentic-GCN.git

%cd /content/Sentic-GCN

!pip install pytorch_pretrained_bert

!pip install ipdb

!python dependency_graph.py  to generate .graph files

!python sentic_dependency_graph.py

rename .graph_sdat_60 files to .graph_sdat

!python /content/Sentic-GCN/generate_sentic_graph.py to generate .sentic files

!CUDA_VISIBLE_DEVICES=1 python3 train_bert.py --model_name senticgcn_bert --dataset rest14 --save True --learning_rate 2e-5 --seed 39 --batch_size 16 --hidden_dim 768

NB: an error first occurs when executing the train_bert.py file

   seq_len = len(x[1])
IndexError: index 1 is out of bounds for dimension 0 with size 1

I fixed it by removing seq_len = len(x[1]) and computing seq_len using  seq_len = x.shape[1]


Am I doing something wrong?

Thank u in advance

**Comment by BinLiang-NLP** [comment]
> First, a big thanks for ur quick responses, I really appreciate that. However, the problem still persists
> 
> Here are the steps I follow to run the code
> 
> !wget https://sentic.net/senticnet-6.0.zip
> 
> !unzip /content/senticnet-6.0.zip
> 
> !pip install spacy
> 
> !python -m spacy download en
> 
> !git clone https://github.com/SenticNet/Sentic-GCN.git
> 
> %cd /content/Sentic-GCN
> 
> !pip install pytorch_pretrained_bert
> 
> !pip install ipdb
> 
> !python dependency_graph.py to generate .graph files
> 
> !python sentic_dependency_graph.py
> 
> rename .graph_sdat_60 files to .graph_sdat
> 
> !python /content/Sentic-GCN/generate_sentic_graph.py to generate .sentic files
> 
> !CUDA_VISIBLE_DEVICES=1 python3 train_bert.py --model_name senticgcn_bert --dataset rest14 --save True --learning_rate 2e-5 --seed 39 --batch_size 16 --hidden_dim 768
> 
> NB: an error first occurs when executing the train_bert.py file
> 
> seq_len = len(x[1]) IndexError: index 1 is out of bounds for dimension 0 with size 1
> 
> I fixed it by removing seq_len = len(x[1]) and computing seq_len using seq_len = x.shape[1]
> 
> Am I doing something wrong?
> 
> Thank u in advance

Hi,
I have fixed the errors.
You don't need to rename the .graph_sdat_60 files to .graph_sdat.
Please refer to the content of README to run the code.
Thanks a lot for your insightful issues.
Please let me know if there is any problem.

**Comment by karimmahalian** [comment]
Hi,

Thank you for taking the time to answer my questions. However, I followed the steps in README and I still got the same performance. Could u plz try to run the code to check? It would be awesome if u could share it with me on google colab.

I really appreciate ur effort to help me with this issue.

Thank u

**Comment by BinLiang-NLP** [comment]
> Hi,
> 
> Thank you for taking the time to answer my questions. However, I followed the steps in README and I still got the same performance. Could u plz try to run the code to check? It would be awesome if u could share it with me on google colab.
> 
> I really appreciate ur effort to help me with this issue.
> 
> Thank u

Hi,
I re-clone the repository to my machine and operate it according to the instructions of the README. The training process is normal and there is no problem. Just like that:
![image](https://user-images.githubusercontent.com/20014345/145357045-7751c874-58da-4d6d-b164-db1c4b984668.png)

Therefore, I suggest you clone the repository again, and you can get the correct training process.
Please let me know if there is any problem.
Thanks!

**Comment by karimmahalian** [comment]
Yes, It works!! thank u very much for ur help.
Could u plz tell me how did u get the senticnet_word.txt file? I need to generate it for another language than English.

Thanks again

**Comment by yassmine-lam** [comment]
Hi,

The same request plz. Could u share the way to build the senticnet_word.txt file for another language?

Many thanks in advance

**Comment by BinLiang-NLP** [comment]
> Yes, It works!! thank u very much for ur help. Could u plz tell me how did u get the senticnet_word.txt file? I need to generate it for another language than English.
> 
> Thanks again

Hi,
I have added the code for generating the senticnet_word.txt file. Please refer to **handle_senticNet.py**.
Since the source of SenticNet is with a clear structure, I'm not sure whether this code can be directly applicable to other knowledge bases.
Please let me know if there is any problem.
Thanks!

**Comment by BinLiang-NLP** [comment]
> Hi,
> 
> The same request plz. Could u share the way to build the senticnet_word.txt file for another language?
> 
> Many thanks in advance

Hi,
I have added the code for generating the senticnet_word.txt file. Please refer to handle_senticNet.py.
Since the source of SenticNet is with a clear structure, I'm not sure whether this code can be directly applicable to other knowledge bases.
Please let me know if there is any problem.
Thanks!

**Comment by karimmahalian** [comment]
@BinLiang-NLP  Thank u very much for the code. I will check it for my knowledge base.
Could u please tell me if u examined using a sentiment lexicon instead of SenticNet? 

Thanks again

**Comment by BinLiang-NLP** [comment]
> @BinLiang-NLP Thank u very much for the code. I will check it for my knowledge base. Could u please tell me if u examined using a sentiment lexicon instead of SenticNet?
> 
> Thanks again

Hi,
Yes, we did use other knowledge sources in the preliminary experiments, such as ConceptNet, WordNet, etc.
Our proposed framework is effective no matter what knowledge base or sentiment lexicon is used, as long as it contains words and sentiment scores of words.
Please see the **_senticnet_word.txt_** file. We only need words and the corresponding sentiment scores to construct and run the proposed model.
That is, the knowledge base or sentiment lexicon could be very general. Not only English but also other languages.
Thanks!

**Comment by karimmahalian** [comment]
Of curse, I will :)

Thank u very much for ur help.
